# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 727)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".images/whitebooklogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #创建主窗口的水平布局
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        #创建树结构菜单栏
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setMinimumSize(QtCore.QSize(140, 0))
        self.treeWidget.setObjectName("treeWidget")
        self.horizontalLayout.addWidget(self.treeWidget)
        #设置菜单栏标题隐藏
        self.treeWidget.header().setVisible(False)
        #创建根菜单
        root = QtWidgets.QTreeWidgetItem(self.treeWidget)
        root.setText(0, "数据处理")
        root.setIcon(0, QtGui.QIcon("./images/data.png"))
        #创建根菜单下的子菜单1
        leadData = QtWidgets.QTreeWidgetItem(root)
        leadData.setText(0, "导入数据")
        leadData.setIcon(0, QtGui.QIcon("./images/leadData2.png"))
        # 创建根菜单下的子菜单2
        relation = QtWidgets.QTreeWidgetItem(root)
        relation.setText(0, "创建关系")
        relation.setIcon(0, QtGui.QIcon("./images/relation.png"))
        # 创建根菜单下的子菜单3
        select = QtWidgets.QTreeWidgetItem(root)
        select.setText(0, "筛选数据")
        select.setIcon(0, QtGui.QIcon("./images/select.png"))
        # 创建根菜单下的子菜单4
        export = QtWidgets.QTreeWidgetItem(root)
        export.setText(0, "导出数据")
        export.setIcon(0, QtGui.QIcon("./images/export.png"))
        #创建MDI窗口
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.horizontalLayout.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "建河工具系统"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "窗口"))
